server:
  port: 7091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_init?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  profiles:
    active: dev
