server:
  port: 7091
spring:
  profiles:
    active: dev
#    baGuMi地址信息
bgm:
  url:
#    排行url
    rank: https://bgm.tv/anime/browser
    base: https://api.bgm.tv

  agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71